export const style = {
  map: {
    position: 'absolute',
    width: '100%',
    height: '100vh',
    zIndex: 0,
  } as React.CSSProperties,
  button: {
    position: 'absolute',
    left: 'calc(50% - 65px)',
    top: '10px',
    zIndex: 1000,
    width: '144px',
    lineHeight: '32px',
    border: '1px solid #999',
    borderRadius: '4px',
    backgroundColor: '#fff',
    cursor: 'pointer',
  } as React.CSSProperties,
  ul: {
    padding: '16px',
    textAlign: 'center',
    backgroundColor: '#fff',
    border: '1px solid #999',
    borderRadius: '4px',
    listStyleType: 'none',
    position: 'absolute',
    margin: 0,
    right: '10px',
    top: '80px',
  } as React.CSSProperties,
  li: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    border: '2px solid #fff',
    cursor: 'pointer',
    margin: '24px 0',
  } as React.CSSProperties,
};
